import React, { useState } from "react";

import RecordingDeck from "../components/RecordingDeck";
import { Link, Clipboard, CheckCircle, Video } from "lucide-react";
import { toast } from "sonner";
import AppShell from "@/components/layout/AppShell";

export default function RecordPage() {
    const [uploadedVideoId, setUploadedVideoId] = useState(null);

    const handleUploadSuccess = (backendResponseData) => {
        // Grab the _id or id generated by your MongoDB backend
        console.log("VideoFlow Upload Response:", backendResponseData);
        // 🎯 THE FIX: Target the nested file structure returned by your controller
        const videoId = backendResponseData?.file?._id;
        // const videoId = backendResponseData._id || backendResponseData.id || backendResponseData.videoId;
        setUploadedVideoId(videoId);
    };

    const getShareUrl = () => {
        const apiBaseUrl = import.meta.env.VITE_API_URL || "http://localhost:3000";

        // 🧼 FIXED: Points directly to your server-side getWatchPage route!
        return `${apiBaseUrl}/files/${uploadedVideoId}/watch`;
     //   return `${window.location.origin}/v/${uploadedVideoId}`;
    };

    const copyShareLink = () => {
        navigator.clipboard.writeText(getShareUrl());
        toast.success("🔗 Public share link copied to clipboard!");
    };

    return (
        <AppShell>
            <div className="p-6 max-w-3xl mx-auto space-y-8">
                <div>
                    <h1 className="text-2xl font-bold tracking-tight">Instant Record Studio</h1>
                    <p className="text-xs text-muted-foreground mt-1">
                        Capture your thoughts, window selections, or walk-throughs and get a shareable deployment link instantly.
                    </p>
                </div>

                {!uploadedVideoId ? (
                    // 🎥 STATE A: Live Recorder Deck Component Wrapper
                    <RecordingDeck onUploadComplete={handleUploadSuccess} />
                ) : (
                    // 🔗 STATE B: Instant Share Link HUD (Triggers right after video hits the server)
                    <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/[0.01] p-8 text-center space-y-5 shadow-lg max-w-2xl mx-auto animate-in fade-in zoom-in-95 duration-200">
                        <div className="mx-auto h-12 w-12 rounded-full bg-emerald-500/10 flex items-center justify-center text-emerald-400">
                            <CheckCircle className="h-6 w-6" />
                        </div>

                        <div className="space-y-1">
                            <h3 className="text-base font-semibold text-foreground">Video Sent to Ingestion Pipelines!</h3>
                            <p className="text-xs text-muted-foreground max-w-sm mx-auto">
                                Your adaptive HLS bitrate ladders and pixel watermarks are processing in the background. Your sharing link is live right now:
                            </p>
                        </div>

                        {/* Interactive Link Display Box */}
                        <div className="flex items-center gap-2 bg-background px-4 py-3 rounded-lg border border-border font-mono text-xs text-foreground justify-between max-w-md mx-auto">
                            <span className="truncate text-muted-foreground select-all">{getShareUrl()}</span>
                            <button
                                type="button"
                                onClick={copyShareLink}
                                className="text-primary hover:text-primary/80 ml-3 shrink-0 p-1 hover:bg-muted rounded transition-colors"
                                title="Copy Public Share Link"
                            >
                                <Clipboard className="h-4 w-4" />
                            </button>
                        </div>

                        <div className="flex items-center gap-3 justify-center pt-2">
                            <button
                                type="button"
                                onClick={() => setUploadedVideoId(null)}
                                className="border border-border hover:bg-white/5 text-xs font-semibold px-4 py-2 rounded-lg transition-colors flex items-center gap-1"
                            >
                                <Video className="h-3.5 w-3.5" /> Record Another
                            </button>
                            <a
                                href={`/videos/${uploadedVideoId}`}
                                className="bg-secondary text-secondary-foreground hover:bg-secondary/80 text-xs font-semibold px-4 py-2 rounded-lg transition-colors inline-flex items-center gap-1"
                            >
                                View Creator Analytics
                            </a>
                        </div>
                    </div>
                )}
            </div>
        </AppShell>
    );
}